mysite/polls/urls.py
# URLconfをpollsディレクトリに作る。
# ビューを呼ぶためのURLが対応付けされる
from django.urls import path

from . import views
# path()
# アプリケーションの名前空間を設定、複数のアプリのビューを区別する。
app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # 第一引数が、urlの情報、第二引数が、左の条件を満たす時に、参照するパス
    # 第３引数が、上記パターンの名前
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results,
    name = 'results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models
# スキーマは、データベースで多数のテーブルを作るときに、
# テーブルごとに分類するための仕組み：ディレクトリに相当
# テーブル(表)とは、作成されたファイルに相当
# このコードによって、アプリケーションのデータスキーマを作成できる
# つまりcreate table文を実行できる
# questionやchoiceオブジェクトにpythonからアクセスするためのデータベースAPIを作成できる
# API：Application programming interface
# アプリとアプリの間でデータをやり取りする方法(google mapとかは
# APIをbingmapとかから取得している。
# Web APIはhttpでリクエストを送受信する仕組み
# データは一般的にjsonやxmlが使われている
# SaaS(Software as a Service)からデータをやり取りをする際にとても重要です。
# アプリ  →(このデータをください(HTTP))　webサーバ
# アプリ　 ← (データだけをどうぞ(HTTP)json,xml形式) Webサーバ 
# SaaSとは、ネット経由でソフトを利用できる形態。
# Create your models here.
# 2つのモデルを作成、モデル＝1:データベースのレイアウト
# 2:データベースのメタデータとなっている。
# 個々のクラス変数はデータベースのフィールド
class Question(models.Model): 
    question_text = models.CharField(max_length=200) # 文字のフィールド
    pub_date = models.DateTimeField('date published')  # 日時のフィールド
    # 上の二つのフィールド指定で、どんなデータ型を記憶されるかをdjangoに教える
    # Question.pub_dataの中身は、人間に可読なフィールド名
    # Fieldクラスの中には必須の引数がいる。max_lengthがそれ。
    def __str__(self):
        return self.question_text

    
class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE)
    # ForeignKeyは依存関係にある2つの表を結びつける
    # 入力変数の値の候補を指定する
    # 今回はChoiceが1つのQuestionに関連づけられる
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    # defaultはオプション引数
  
    def __str__(self):
        return self.choicen_text

mysite/polls/views.py
from django.http import HttpResponse
# http://php6.jp/python/2011/01/21/string_format/
# %の意味について文字列中の%sの部分が、後ろに与えられた引数で置換される。
# viewの役割・・・１：リクエストされたページのコンテンツを含むオブジェクトを返す
# ２：Http404のような例外の送出
from django.http import Http404
from django.template import loader
from django.shortcuts import get_object_or_404, render

from .models import Question

def index(request):
    # 並べ替え
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # modelclass.modelmanager.method()という形でクエリを実行
    # template = loader.get_template('polls/index.html')
    context = {'latest_question_list':latest_question_list}
    # output = ', '.join([q.question_text for q in latest_question_list])
    # 区切り文字.join(list)として、区切り文字を入れて連結できる
    # システム上の最新5件の質問をカンマで区切り、日付順に表示
    # rendering表示用のデータを元に、内容を整形して表示すること
    # マッピング：対応づけること？
    # テンプレートを指定のコンテキストでレンダリングし、そのHttpResponseオブジェクトを返す。
    return render(request, 'polls/index.html', context)
    # return HttpResponse(template.render(context, request)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
    # return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
# Create your views here

mysite/polls/templates/polls/detail.html
<h1>{
  {question.question_txt}
  }</h1>
{% if error_message %}
<p>
  <strong>{
    { error_message }
    }</strong>
</p>
{% endif %}

<form action="[% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ hoice.id }}">
  <label for ="choide{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{
    { choice.choice_text }
    }</li>
  {% end for %}
 </ul> 

mysite/polls/templates/polls/index.html
<!-- {%は、テンプレートタグと呼ばれ、その部分で何かしらテンプレートの動作(ループなど)
をさせることを表す。-->
{% if latest_question_list %}
<!--- <ul>タグはUnordered listの略。順序のないリストを表示するのに使用する。
<li>でリストの各項目を記述する。
<a>タグはアンカーの略。リンクの出発点と到達点を指定する。
出発点ではhref属性でリンク先を指定する。-->
<ul>
  {% for question in latest_question_list %}
  <li><a href="{% url 'polls:detail' question.id %}">{{
      question.question_text }}</a></li>
  {% endfor %}
</ul>
{% else %}
<!--- <p>はparagraphの略。囲まれた部分が一つの段落であることを表す。-->
<p>No polls are available.</p>
{% endif %}